services:
  # ------------------ Frontend ------------------
  frontend:
    image: 505646497781.dkr.ecr.us-east-1.amazonaws.com/geosphere/frontend:latest
    container_name: frontend
    restart: always
    ports:
      - "0.0.0.0:3000:3000"
    depends_on:
      - agent
    networks:
      - net_frontend_agent

  # ------------------ Agent ------------------
  agent:
    image: 505646497781.dkr.ecr.us-east-1.amazonaws.com/geosphere/agent:latest
    container_name: agent
    restart: always
    secrets:
      - langfuse_host
      - langfuse_public_key
      - langfuse_secret_key
      - openai_api_key
      - jwt_secret_key
      - users
      - vertex_auth.json
      - aws_bearer_token_bedrock
    depends_on:
      - datawarehouse_mcp
      - rag_mcp
      - geospatial_mcp
    networks:
      - net_frontend_agent
      - net_agent_datawarehouse
      - net_agent_rag
      - net_agent_geospatial
    environment:
      - ENVIRONMENT=prod

  # ------------------ Data-Warehouse MCP ------------------
  datawarehouse_mcp:
    image: 505646497781.dkr.ecr.us-east-1.amazonaws.com/geosphere/datawarehouse:latest
    container_name: datawarehouse_mcp
    restart: always
    networks:
      - net_agent_datawarehouse

  # ------------------ RAG MCP ------------------
  rag_mcp:
    image: 505646497781.dkr.ecr.us-east-1.amazonaws.com/geosphere/rag:latest
    container_name: rag_mcp
    restart: always
    networks:
      - net_agent_rag

  # ------------------ Geospatial (GEE) MCP ------------------
  geospatial_mcp:
    image: 505646497781.dkr.ecr.us-east-1.amazonaws.com/geosphere/gee:latest
    container_name: geospatial_mcp
    restart: always
    secrets:
      - ee_auth.json
    networks:
      - net_agent_geospatial

  # ------------------ Watchtower ------------------
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - AWS_REGION=us-east-1
      - WATCHTOWER_AWS_AUTOSCAN=true
      - WATCHTOWER_POLL_INTERVAL=300
    command: --cleanup frontend agent datawarehouse_mcp rag_mcp geospatial_mcp

# ------------------ Networks ------------------
networks:
  net_frontend_agent:
    driver: bridge
  net_agent_datawarehouse:
    driver: bridge
  net_agent_rag:
    driver: bridge
  net_agent_geospatial:
    driver: bridge

# ------------------ Secrets ------------------
secrets:
  langfuse_host:
    file: ./.secrets/langfuse_host.txt
  langfuse_public_key:
    file: ./.secrets/langfuse_public_key.txt
  langfuse_secret_key:
    file: ./.secrets/langfuse_secret_key.txt
  openai_api_key:
    file: ./.secrets/openai_api_key.txt
  jwt_secret_key:
    file: ./.secrets/jwt_secret_key.txt
  ee_auth.json:
    file: ./.secrets/ee_auth.json
  users:
    file: ./.secrets/users.json
  vertex_auth.json:
    file: ./.secrets/vertex_auth.json
  aws_bearer_token_bedrock:
    file: ./.secrets/aws_bearer_token_bedrock.txt
