[project]
name = "unicef-geospatial"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "earthengine-api>=1.5",
    "fastapi>=0.115.8",
    "geemap",
    "ipykernel>=6.29.5",
    "langchain>=0.3.18",
    "langchain-cohere>=0.4.2",
    "langchain-openai>=0.3.4",
    "langfuse>=2.59.2",
    "langgraph>=0.2.70",
    "litellm>=1.61.0",
    "pre-commit>=4.1.0",
    "pycountry>=24.6.1",
    "pydantic>=2.10.6",
    "pytest>=8.3.4",
    "pytest-asyncio>=0.25.3",
    "pytest-xdist>=3.6.1",
    "python-jose>=3.4.0",
    "python-multipart>=0.0.20",
    "pyyaml>=6.0.2",
    "setuptools>=75.8.0",
    "uvicorn>=0.34.0",
    "vulture>=2.14",
    "xyzservices @ git+https://github.com/geopandas/xyzservices.git",
]

[tool.uv.sources]
geemap = { git = "https://github.com/gee-community/geemap.git" }
